# Generated by Django 2.1.5 on 2019-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190109_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=50, verbose_name='博客作者（留空默认为添加者名称）'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='博客标签（逗号分隔）'),
        ),
    ]
