# Generated by Django 2.1.5 on 2019-01-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190110_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, default='日记', max_length=50, verbose_name='博客分类（默认值为日记）'),
        ),
    ]
