# Generated by Django 2.1.5 on 2019-01-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190110_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critic', models.CharField(max_length=50, verbose_name='名称')),
                ('portrait', models.ImageField(upload_to='', verbose_name='头像')),
                ('content', models.TextField(blank=True, max_length=600, verbose_name='內容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
            ],
        ),
    ]
