# Generated by Django 2.1.5 on 2019-01-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_criticism'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticism',
            name='article_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
            preserve_default=False,
        ),
    ]
