# Generated by Django 2.1.5 on 2019-01-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_criticism_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticism',
            old_name='article_id',
            new_name='article',
        ),
    ]
