# Generated by Django 2.1.5 on 2019-01-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190110_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticism',
            options={'ordering': ['-pub_date'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterField(
            model_name='criticism',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='关联文章'),
        ),
    ]
