# Generated by Django 2.1.5 on 2019-01-10 17:22

import DjangoUeditor.models
import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190110_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='content',
            field=models.TextField(blank=True, max_length=600, verbose_name='评语'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='critic',
            field=models.CharField(max_length=50, verbose_name='署名'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='portrait',
            field=models.ImageField(upload_to=blog.models.portrait_path, verbose_name='头像'),
        ),
    ]
