# Generated by Django 2.1.5 on 2019-01-10 21:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190111_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=50, verbose_name='作者（留空默认为添加者名称）'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, default='日记', max_length=50, verbose_name='分类（默认值为日记）'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='标签（逗号分隔）'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='critic',
            field=models.CharField(blank=True, max_length=50, verbose_name='署名'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.portrait_path, verbose_name='头像'),
        ),
    ]
