# Generated by Django 2.1.5 on 2019-01-11 20:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190111_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticism',
            name='portrait',
            field=models.ImageField(blank=True, default='portraits/default.png', upload_to=blog.models.portrait_path, verbose_name='头像'),
            preserve_default=False,
        ),
    ]
