# Generated by Django 2.1.5 on 2019-01-12 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190112_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticism',
            name='content',
            field=models.TextField(blank=True, max_length=600, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='评语'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='critic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='署名'),
        ),
    ]
