# Generated by Django 2.1.5 on 2019-01-12 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190112_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticism',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='关联文章'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='critic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='署名'),
        ),
    ]
