# Generated by Django 2.1.5 on 2019-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190113_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.CharField(blank=True, max_length=50, verbose_name='所属'),
        ),
    ]
